version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: 'azure_dni_nginx'
        depends_on:
            - 'dni'
            - 'postgres'
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
        - 9000:9000
    dni:
        image: dni_local:latest
        container_name: 'azure_dni'
        depends_on:
            - 'postgres'
        env_file:
            - dni/dni.env
        ports:
            - 5000:5000
        restart: always
    postgres:
        # https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions
        image: postgres:11.6
        container_name: 'azure_dni_postgres'
        environment:
            - POSTGRES_USER=dni
            - POSTGRES_PASSWORD=dn1
            - POSTGRES_DB=dni_database
        volumes:
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 4321:5432
    pgadmin:
        image: dpage/pgadmin4:5.4
        container_name: 'azure_dni_pgadmin4'
        environment: 
            - PGADMIN_DEFAULT_EMAIL=dni@tesco.com
            - PGADMIN_DEFAULT_PASSWORD=dn1
        ports:
            - 4343:80
            