const ROOT = 'notifications';
const GET_LIST_ACTION = `${ROOT}/list`;
const GET_LIST_NETWORKS_ACTION = `${ROOT}/networks/list`;
const ACKNOWLEDGE_ACTION = `${ROOT}/acknowledge`;
const TOGGLE_SIDEBAR_ACTION = `${ROOT}/toggle-sidebar`;
const GET_PERSONAL_EMAIL = `${ROOT}/email`;
const GET_NOTIFICATION_SETTINGS = `${ROOT}/notification-settings`;
const UPDATE_PERSONAL_EMAIL = `${ROOT}/update-email`;
const CREATE_PERSONAL_EMAIL = `${ROOT}/create-email`;
const UPDATE_NOTIFICATION_SETTINGS = `${ROOT}/update-notification-settings`;

export {
  ROOT,
  GET_LIST_ACTION,
  GET_LIST_NETWORKS_ACTION,
  ACKNOWLEDGE_ACTION,
  TOGGLE_SIDEBAR_ACTION,
  GET_PERSONAL_EMAIL,
  GET_NOTIFICATION_SETTINGS,
  UPDATE_PERSONAL_EMAIL,
  CREATE_PERSONAL_EMAIL,
  UPDATE_NOTIFICATION_SETTINGS,
};
