version: '3'
services:
  database:
    image: 'postgres:11.6'
    container_name: 'dni-postgresql'
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    restart: always
